name: EscapePlug
main: net.escapecraft.escapePlug.EscapePlug
version: 0.1.2
commands:
    pig-active:
        description: Activate pig punching
        usage: /<command>
    pig-deactive:
        description: deactivate pig punching
        usage: /<command>
    mentor:
        description: Teleports you to a builder or default
        usage: /mentor <player>