name: EscapePlug
main: net.escapecraft.escapePlug.EscapePlug
version: ${project.version}
softdepend: [DroxPerms, BeardStat]
commands:
    pig-active:
        description: Activate pig punching
        usage: /<command>
        permission: escapeplug.pigjoust
    pig-deactive:
        description: deactivate pig punching
        usage: /<command>
        permission: escapeplug.pigjoust
    mentortp:
        description: Teleports you to a builder or default
        usage: /mentortp <player>
        permission: escapeplug.mentor.teleport
    mentorback:
        description: Teleports you back to your previous location
        usage: /mentorback 
        permission: escapeplug.mentor.teleport
    timezone:
        description: shows and converts timezones
        usage: /<command>
        aliases: [tz, clock]
    togglemode:
        description: Toggles gamemode
        usage: /<command>
    lockdown:
        description: Changes lockdown mode
        usage: |
            /<command> enable - Enables Lockdown-Mode
            /<command> disable - Disables Lockdown-Mode
        permission: escapeplug.lockdown.change
    hat:
        aliases: [hat, hatme, hm]
        description: Command that puts the item on your head.
        usage: /<command> [item id]- puts item on head [puts item on head from item id]
    unhat:
        aliases: [unhat, unhatme, unhm]
        description: Command to take your "hat" off.
        usage: /<command> - takes item off head
    who:
        description: Gives Information about the online Players.
        usage:  |
            /<command> - Lists online Players
            /<command> <name> - Gives Information about a Player
    afkbooter:
        description: Kicks afk players after specified idle time.
        usage: |
            /<command> list - List the players on the exempt list.
            /<command> add <name> ... - Add players to the exempt list.
            /<command> remove <name> ... - Remove players from the exempt list.

permissions:
  escapeplug.*:
    description: Supernode for EscapePlug commands.
    children:
      escapeplug.pigjoust: true
      escapeplug.mentor.teleport: true
      escapeplug.mentor.teleport.notarget: true
      escapeplug.gamemode: true
      escapeplug.lockdown: true
      escapeplug.notify: true
      escapeplug.hatme: true
      escapeplug.who: true
      escapeplug.afkbooter: true
  escapeplug.lockdown:
    description: gives full permission on Lockdown-mode.
    children:
      escapeplug.lockdown.allow: true
      escapeplug.lockdown.change: true
  escapeplug.hatme:
    description: gives full permission on Hatme.
    children:
      escapeplug.hatme.hat: true
      escapeplug.hatme.give: true
      escapeplug.hatme.norestrict: true
  escapeplug.who:
    description: gives full permission on Who.
    children:
      escapeplug.who.list: true
      escapeplug.who.player: true
  escapeplug.afkbooter:
    description: gives full permission on AfkBooter.
    children:
      escapeplug.afkbooter.config: true
      escapeplug.afkbooter.exempt: true
  escapeplug.afkbooter.config:
    description: Allows players to change AfkBooter configuration.
    default: op
  escapeplug.afkbooter.exempt:
    description: Exempts players from being kicked by AfkBooter when idling.
    default: op
  escapeplug.lockdown.allow:
    description: Allows players to join while Lockdown-mode.
    default: op
  escapeplug.lockdown.change:
    description: Allows players to change Lockdown-mode.
    default: op
  escapeplug.lockdown.notify:
    description: Notify Players about active Lockdown-mode on join.
    default: op
  escapeplug.mentor.teleport:
    description: Allows Mentors to teleport to other Players.
    default: op
  escapeplug.mentor.teleport.notarget:
    description: Disallows Mentors to teleport to this Player.
    default: op
  escapeplug.pigjoust:
    default: op
  escapeplug.gamemode:
    default: op
  escapeplug.hatme.hat:
    description: Allows player to use given item as a hat
    default: op
  escapeplug.hatme.give:
    description: Allows player to use item in hand as a hat
    default: op
  escapeplug.hatme.norestrict:
    description: Player Overwrites the block-restriction
    default: op
  escapeplug.who.list:
    description: Shows the Player-list
    default: op
  escapeplug.who.player:
    description: Shows details on specific Players
    default: op
