name: EscapePlug
main: net.escapecraft.escapePlug.EscapePlug
version: 0.1.0
commands:
    pig-active:
        description: Activate pig punching
        usage: /<command>
        permission: escapeplug.pigjoust
    pig-deactive:
        description: deactivate pig punching
        usage: /<command>
        permission: escapeplug.pigjoust
    mentortp:
        description: Teleports you to a builder or default
        usage: /mentortp <player>
        permission: escapeplug.mentor.teleport
    mentorback:
        description: Teleports you back to your previous location
        usage: /mentorback 
        permission: escapeplug.mentor.teleport
    timezone:
        description: shows and converts timezones
        usage: /<command>
        aliases: [tz, clock]
    togglemode:
        description: Toggles gamemode
        usage: /<command>
    lockdown:
        description: Changes lockdown mode
        usage: |
            /<command> enable - Enables Lockdown-Mode
            /<command> disable - Disables Lockdown-Mode
        permission: escapeplug.lockdown.change
    hat:
      aliases: [hat, hatme, hm]
      description: Command that puts the item on your head.
      usage: /<command> [item id]- puts item on head [puts item on head from item id]
    unhat:
      aliases: [unhat, unhatme, unhm]
      description: Command to take your "hat" off.
      usage: /<command> - takes item off head

permissions:
  escapeplug.*:
    description: Supernode for EscapePlug commands.
    children:
      escapeplug.pigjoust: true
      escapeplug.mentor.teleport: true
      escapeplug.mentor.teleport.notarget: true
      escapeplug.gamemode: true
      escapeplug.lockdown: true
      escapeplug.notify: true
      escapeplug.hatme: true
  escapeplug.lockdown:
    description: gives full permission on Lockdown-mode.
    children:
      escapeplug.lockdown.allow: true
      escapeplug.lockdown.change: true
  escapeplug.hatme:
    description: gives full permission on Hatme.
    children:
      escapeplug.hatme.hat: true
      escapeplug.hatme.give: true
      escapeplug.hatme.norestrict: true
  escapeplug.lockdown.allow:
    description: Allows players to join while Lockdown-mode.
    default: op
  escapeplug.lockdown.change:
    description: Allows players to change Lockdown-mode.
    default: op
  escapeplug.lockdown.notify:
    description: Notify Players about active Lockdown-mode on join.
    default: op
  escapeplug.mentor.teleport:
    description: Allows Mentors to teleport to other Players.
    default: op
  escapeplug.mentor.teleport.notarget:
    description: Disallows Mentors to teleport to this Player.
    default: op
  escapeplug.pigjoust:
    default: op
  escapeplug.gamemode:
    default: op
  escapeplug.hatme.hat:
    description: Allows player to use given item as a hat
    default: op
  escapeplug.hatme.give:
    description: Allows player to use item in hand as a hat
    default: op
  escapeplug.hatme.norestrict:
    description: Player Overwrites the block-restriction
    default: op